### ISSUE TITLE
Spawn cost overflow with a big number of spawned units 

### ISSUE THREAD

**Issue by jerem-ma** [CodinGame/FallChallenge2022-KeepOffTheGrass#6]
Hey !
If a player try to spawn an amount of units >= 214748365, an overflow occurs because of a multiplication by 10, causing the variable to overflow and become negative.
Fixed in #5

**Comment by CGjupoulton** [comment]
Fixed in https://github.com/CodinGame/FallChallenge2022-KeepOffTheGrass/commit/76942694c0d80996e72711e904878bb0e972b6ea
